### ISSUE TITLE
Plan database schema

### ISSUE THREAD

**Issue by JonasEbbinghaus25** [SE-TINF22B6/DHBWhub#32]
Description:

- Goal: This ticket aims to plan and create the database schema for the Forum project.
- Responsibilities: The team will design the database schema that defines the structure for storing user data, posts, and related information.
- Outcome: A complete database schema that defines the structure of the Forum database.

Acceptance Criteria:
- A documented database schema.

**Comment by FurKay00** [comment]
First rough sketch of database schema done, can found it under: https://github.com/SE-TINF22B6/DHBWhub/blob/master/docs/ER_Diagram_First_Version.drawio.png
